# Generated by Django 6.0.7 on 2026-08-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_add_shoes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
