# Generated by Django 6.0.7 on 2026-08-13 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aesthetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='aesthetics/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order (lower first).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aesthetic',
                'verbose_name_plural': 'Aesthetics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in centimeters.', null=True)),
                ('body_type', models.CharField(blank=True, choices=[('slim', 'Slim'), ('athletic', 'Athletic'), ('average', 'Average'), ('curvy', 'Curvy'), ('plus_size', 'Plus Size')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text="Set once the user finishes the post-signup 'Complete Profile' step.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aesthetics', models.ManyToManyField(blank=True, related_name='customer_profiles', to='accounts.aesthetic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
