# Generated by Django 6.0.7 on 2026-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='internal_error_detail',
            field=models.TextField(blank=True),
        ),
    ]
