# Generated by Django 6.0.7 on 2026-08-08 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0002_avatar_internal_error_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='avatar',
            name='style',
            field=models.CharField(choices=[('realistic', 'Realistic'), ('cartoon', 'Cartoon')], db_index=True, default='realistic', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='source_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/source/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL),
        ),
    ]
