# Generated by Django 6.0.7 on 2026-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0004_avatar_unique_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='fal_cdn_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
