# Generated by Django 6.0.7 on 2026-08-18 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0005_avatar_fal_cdn_url_avatar_is_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avatar',
            name='unique_default_avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='is_preferred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='avatar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default', 'gender', 'style'), name='unique_system_default_avatar_per_gender_style'),
        ),
        migrations.AddConstraint(
            model_name='avatar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('user',), name='unique_preferred_avatar_per_user'),
        ),
    ]
