# Generated by Django 6.0.7 on 2026-08-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0003_outfitjob_reasoning_items_outfitjob_reasoning_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('fal_request_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('result_mesh', models.FileField(blank=True, null=True, upload_to='model3d/meshes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d_conversions', to='outfits.outfitjob')),
            ],
            options={
                'verbose_name': '3D Conversion',
                'verbose_name_plural': '3D Conversions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'done'])), fields=('outfit_job',), name='unique_active_or_done_conversion_per_outfit_job')],
            },
        ),
    ]
