# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wardrobe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrobeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="wardrobe_items/originals/"),
                ),
                (
                    "season",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "occasion",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "purchase_source",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="wardrobe.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wardrobe Item",
                "verbose_name_plural": "Wardrobe Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="wardrobe_items_ai/processed/",
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "fal_request_id_bg_removal",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "fal_request_id_vision",
                    models.CharField(blank=True, max_length=100),
                ),
                ("error_message", models.TextField(blank=True)),
                ("internal_error_detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wardrobe_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="wardrobe_items_ai.wardrobeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Analysis",
                "verbose_name_plural": "Item Analyses",
            },
        ),
    ]
