# Generated by Django 6.0.7 on 2026-08-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('sport', 'Sport'), ('wedding', 'Wedding'), ('work', 'Work')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('all_season', 'All Season')], max_length=50),
        ),
    ]
