# Generated by Django 6.0.7 on 2026-08-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0002_alter_wardrobeitem_occasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemanalysis',
            name='fal_cdn_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
