# Generated by Django 6.0.7 on 2026-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0003_itemanalysis_fal_cdn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemanalysis',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
