# Generated by Django 6.0.7 on 2026-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0004_itemanalysis_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemanalysis',
            name='fal_cdn_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
