# Generated by Django 6.0.7 on 2026-08-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0005_alter_itemanalysis_fal_cdn_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(max_length='500', upload_to='wardrobe_items/originals/'),
        ),
    ]
