# Generated by Django 6.0.7 on 2026-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_items_ai', '0006_alter_wardrobeitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(max_length=500, upload_to='wardrobe_items/originals/'),
        ),
    ]
