# Generated by Django 6.0.7 on 2026-08-13 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatars', '__first__'),
        ('wardrobe_items_ai', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('fal_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='outfits/result/')),
                ('error_message', models.TextField(blank=True)),
                ('internal_error_detail', models.TextField(blank=True)),
                ('reasoning_title', models.CharField(blank=True, max_length=255)),
                ('reasoning_subtitle', models.CharField(blank=True, max_length=255)),
                ('reasoning_items', models.JSONField(blank=True, default=list)),
                ('reasoning_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_jobs', to='avatars.avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_jobs', to=settings.AUTH_USER_MODEL)),
                ('wardrobe_items', models.ManyToManyField(related_name='outfit_jobs', to='wardrobe_items_ai.wardrobeitem')),
            ],
            options={
                'verbose_name': 'Outfit Job',
                'verbose_name_plural': 'Outfit Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_entries', to='outfits.outfitjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Outfit',
                'verbose_name_plural': 'Saved Outfits',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='outfitjob',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_type', 'auto')), fields=('user', 'scheduled_date', 'trigger_type'), name='unique_auto_outfit_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='savedoutfit',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_saved_outfit_per_user_per_date'),
        ),
    ]
