# Generated by Django 6.0.7 on 2026-08-09 08:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0004_avatar_unique_default_avatar'),
        ('outfits', '0001_initial'),
        ('wardrobe_items_ai', '0003_itemanalysis_fal_cdn_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
