# Generated by Django 6.0.7 on 2026-08-13 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedoutfit',
            name='is_shared',
            field=models.BooleanField(db_index=True, default=False, help_text="When on, this saved outfit is visible on the user's public profile."),
        ),
        migrations.AddIndex(
            model_name='savedoutfit',
            index=models.Index(fields=['user', 'is_shared', '-date'], name='outfits_sav_user_id_a7b27a_idx'),
        ),
    ]
