# Generated by Django 6.0.7 on 2026-08-09 08:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0004_avatar_unique_default_avatar'),
        ('outfits', '0001_initial'),
        ('wardrobe_items_ai', '0003_itemanalysis_fal_cdn_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitjob',
            name='scheduled_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outfitjob',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='outfitjob',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_type', 'auto')), fields=('user', 'scheduled_date', 'trigger_type'), name='unique_auto_outfit_per_user_per_day'),
        ),
    ]
