# Generated by Django 6.0.7 on 2026-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfitjob_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitjob',
            name='reasoning_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outfitjob',
            name='reasoning_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outfitjob',
            name='reasoning_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outfitjob',
            name='reasoning_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
