# Generated by Django 6.0.7 on 2026-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfitjob_scheduled_date_and_more'),
    ]

    operations = []
