# Generated by Django 6.0.7 on 2026-08-13 10:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_savedoutfit_is_shared_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_harmony', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('trendy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('overall_matching', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('accessories', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_ratings', to=settings.AUTH_USER_MODEL)),
                ('saved_outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='outfits.savedoutfit')),
            ],
            options={
                'verbose_name': 'Outfit Rating',
                'verbose_name_plural': 'Outfit Ratings',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('saved_outfit', 'rater'), name='unique_rating_per_user_per_outfit')],
            },
        ),
    ]
