# Generated by Django 6.0.7 on 2026-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_outfitrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitjob',
            name='fal_cdn_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='outfitjob',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
