# Generated by Django 6.0.7 on 2026-08-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_outfitjob_fal_cdn_url_outfitjob_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitjob',
            name='fal_cdn_url',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
