# Generated by Django 6.0.7 on 2026-08-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_savedoutfit_is_shared_and_more'),
        ('outfits', '0004_savedoutfit'),
    ]

    operations = [
    ]
