# Generated by Django 6.0.7 on 2026-08-25 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0006_alter_savedoutfit_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOutfitSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_selections', to='outfits.outfitjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_outfit_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Outfit Selection',
                'verbose_name_plural': 'Daily Outfit Selections',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_outfit_selection_per_user_per_date')],
            },
        ),
    ]
